name: Publish Invoice Balance Refresher

on:
  push:
    branches: [ main ]
    paths:
      - '**.cs'
      - '**.xaml'
      - '**.csproj'
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Manual trigger option

jobs:
  build:
    runs-on: windows-latest
    
    env:
      SOLUTION_FILE: InvoiceBalanceRefresher.sln
      PROJECT_FILE: InvoiceBalanceRefresher.csproj
      PUBLISH_DIR: publish

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_FILE }}

    - name: Build
      run: dotnet build ${{ env.SOLUTION_FILE }} --configuration Release --no-restore

    - name: Publish Single File
      run: |
        dotnet publish ${{ env.PROJECT_FILE }} `
          --configuration Release `
          --output ${{ env.PUBLISH_DIR }} `
          --runtime win-x64 `
          --self-contained true `
          -p:PublishSingleFile=true `
          -p:IncludeNativeLibrariesForSelfExtract=true `
          -p:PublishReadyToRun=true `
          -p:DebugType=None `
          -p:DebugSymbols=false

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4  # Updated from v3 to v4
      with:
        name: InvoiceBalanceRefresher
        path: ${{ env.PUBLISH_DIR }}/**
        if-no-files-found: error

    - name: Create Release
      if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/')
      id: create_release
      uses: softprops/action-gh-release@v2  # Updated to v2
      with:
        files: |
          ${{ env.PUBLISH_DIR }}/InvoiceBalanceRefresher.exe
        draft: false
        prerelease: false
        name: Invoice Balance Refresher ${{ github.ref_name }}
        body: |
          📋 Release Notes:
          - Single executable file for easy distribution
          - Built on .NET 8 for maximum performance
          - Fallout/Borderlands inspired terminal UI
